#!/bin/sh
# docker-entrypoint.sh — runs at container start.
#
# Goals (in order):
#   1. If conf.d/ is empty (user didn't mount anything), seed it with a
#      built-in fallback vhost so the image boots into a working state.
#   2. Point nginx's `resolver` at whatever DNS the container itself uses.
#   3. If no certificate exists at /etc/letsencrypt/_default/, drop in a
#      throw-away self-signed pair so nginx can boot for local testing.
#      In production, mount your real certs into /etc/letsencrypt/.
#   4. Validate config with `nginx -t`.
#   5. Exec the requested command (default: nginx -g 'daemon off;').
#
# Periodic reload (for cert renewal) is the host's job — run e.g.:
#     docker exec nginx nginx -s reload
# from your certbot --deploy-hook. We do NOT run a sleep-and-reload loop
# inside the container; it would mask crashes and leave zombie sleeps.

set -eu

CERT_DIR="${CERT_DIR:-/etc/letsencrypt}"
DEFAULT_CN="${DEFAULT_CN:-localhost}"
CONFD="${CONFD:-/etc/nginx/conf.d}"
DEFAULT_CONFD="${DEFAULT_CONFD:-/usr/share/nginx-defaults}"
RESOLVER_CONF="${RESOLVER_CONF:-/etc/nginx/resolver.conf}"

# 1. Seed conf.d if empty.
seed_default_confd() {
    [ -d "$CONFD" ] || mkdir -p "$CONFD"
    # If the user mounted their own conf.d, leave it alone.
    if [ -n "$(ls -A "$CONFD" 2>/dev/null)" ]; then
        return 0
    fi
    if [ -d "$DEFAULT_CONFD" ] && [ -n "$(ls -A "$DEFAULT_CONFD" 2>/dev/null)" ]; then
        echo "[entrypoint] conf.d/ is empty, installing built-in fallback vhost"
        cp -a "$DEFAULT_CONFD"/. "$CONFD/"
    fi
}

# 2. Point nginx's resolver at the container's own DNS.
#
#    nginx needs an explicit `resolver` for OCSP stapling and for any
#    proxy_pass whose host comes from a variable. A hardcoded public resolver
#    (what this image shipped previously) is wrong in both directions under
#    Docker: it cannot resolve compose service names at all, and it sends
#    every internal hostname you look up to a third party.
#
#    /etc/resolv.conf is the right source — on a user-defined network it points
#    at Docker's embedded DNS (127.0.0.11), which resolves service names AND
#    forwards public queries upstream; under `network_mode: host` or on
#    Kubernetes it is whatever that environment provides.
#
#    Skipped when the file isn't writable, so mounting your own resolver.conf
#    over it just works.
gen_resolver() {
    # A file the operator bind-mounted read-only is theirs, not ours. Checking
    # the parent directory instead would be wrong here: /etc/nginx stays
    # writable while the mounted file itself does not, so we would sail past
    # the guard and then die on the redirect under `set -e`.
    if [ -e "$RESOLVER_CONF" ] && [ ! -w "$RESOLVER_CONF" ]; then
        echo "[entrypoint] ${RESOLVER_CONF} is read-only, using it as-is"
        return 0
    fi

    # IPv4 nameservers only: an IPv6 resolver would need [bracket] syntax and
    # is vanishingly rare in a container's resolv.conf.
    ns=$(awk '$1 == "nameserver" && $2 !~ /:/ { printf "%s ", $2 }' \
            /etc/resolv.conf 2>/dev/null || true)
    [ -n "$ns" ] || ns="1.1.1.1 8.8.8.8 "

    if cat > "$RESOLVER_CONF" <<EOF
# Generated by docker-entrypoint.sh from /etc/resolv.conf — do not edit.
resolver         ${ns}valid=300s ipv6=off;
resolver_timeout 5s;
EOF
    then
        echo "[entrypoint] resolver: ${ns}"
    else
        echo "[entrypoint] warning: could not write ${RESOLVER_CONF}, using baked-in default"
    fi
}

# 2b. Decide whether QUIC's eBPF socket selector can be switched on.
#
#     `quic_bpf on` is what keeps an HTTP/3 connection alive when a client
#     migrates networks (Wi-Fi → cellular) while `reuseport` is spreading UDP
#     across one socket per worker. Without it those packets reach a worker
#     that has no state for the connection and the client stalls.
#
#     nginx does not degrade when the capability is missing — it refuses to
#     start. Docker grants neither CAP_BPF nor CAP_NET_ADMIN by default, so
#     turning it on unconditionally would break the common case to fix the
#     uncommon one. Hence: detect, then decide.
#
#     QUIC_BPF=on forces it (and lets nginx fail loudly if you were wrong),
#     QUIC_BPF=off disables detection entirely.
CAP_NET_ADMIN=12
CAP_SYS_ADMIN=21
CAP_BPF=39

has_cap() {
    # CapEff is a 64-bit hex mask in /proc/self/status.
    [ -r /proc/self/status ] || return 1
    eff=$(awk '/^CapEff:/ { print $2; exit }' /proc/self/status 2>/dev/null || true)
    [ -n "$eff" ] || return 1
    # ash arithmetic understands 0x literals and is 64-bit here.
    [ "$(( (0x${eff} >> $1) & 1 ))" = "1" ] 2>/dev/null
}

gen_quic_bpf() {
    out=/etc/nginx/quic-bpf.conf
    if [ -e "$out" ] && [ ! -w "$out" ]; then
        echo "[entrypoint] ${out} is read-only, using it as-is"
        return 0
    fi

    decision=""
    case "${QUIC_BPF:-auto}" in
        on)  decision=on  ; why="forced by QUIC_BPF=on" ;;
        off) decision=off ; why="disabled by QUIC_BPF=off" ;;
        *)
            if { has_cap "$CAP_BPF" || has_cap "$CAP_SYS_ADMIN"; } \
               && has_cap "$CAP_NET_ADMIN"; then
                decision=on ; why="CAP_BPF/CAP_SYS_ADMIN + CAP_NET_ADMIN present"
            else
                decision=off
                why="no CAP_BPF/CAP_SYS_ADMIN+CAP_NET_ADMIN; HTTP/3 connection migration will not survive a client network change (docker run --cap-add BPF --cap-add NET_ADMIN)"
            fi
            ;;
    esac

    if [ "$decision" = on ]; then
        body="quic_bpf on;"
    else
        body="# quic_bpf not enabled: ${why}"
    fi

    if printf '# Generated by docker-entrypoint.sh — do not edit.\n%s\n' "$body" > "$out"; then
        echo "[entrypoint] quic_bpf: ${decision} (${why})"
    else
        echo "[entrypoint] warning: could not write ${out}, using baked-in default"
    fi
}

# 3. Ensure a usable default cert exists at _default/.
#    Path matches certbot's `live/<name>/{fullchain,privkey}.pem` layout so
#    real certs are a drop-in replacement.
ensure_default_cert() {
    target="${CERT_DIR}/_default"
    cert="${target}/fullchain.pem"
    key="${target}/privkey.pem"
    [ -f "$cert" ] && [ -f "$key" ] && return 0

    echo "[entrypoint] no default cert found, generating self-signed for CN=${DEFAULT_CN}"
    mkdir -p "$target"
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
        -subj "/CN=${DEFAULT_CN}" \
        -addext "subjectAltName=DNS:${DEFAULT_CN},DNS:localhost,IP:127.0.0.1" \
        -keyout "$key" \
        -out    "$cert" >/dev/null 2>&1
    chmod 600 "$key"
    chmod 644 "$cert"
}

seed_default_confd
gen_resolver
gen_quic_bpf
ensure_default_cert

# 4. If the user passed `nginx ...`, validate config first.
case "${1:-}" in
    nginx|/usr/sbin/nginx)
        echo "[entrypoint] running 'nginx -t'…"
        nginx -t
        ;;
esac

exec "$@"
