name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest Docker image tag
        id: get_latest_tag
        run: |
          latest_tag=$(docker pull hsxk/nginx:latest | awk 'NR==1{print $2}')
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Increment the Docker image tag
        id: increment_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          current_tag=$(echo $latest_tag | awk -F'-' '{print $NF}')
          next_tag=$((current_tag + 1))
          echo "::set-output name=next_tag::$next_tag"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: mainline/alpine/Dockerfile
          push: true
          tags: hsxk/nginx:${{ steps.increment_tag.outputs.next_tag }}
